// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKUa47hsSS_PZjsP8IxQQo1aHis6vMvd0',
    appId: '1:511513353168:web:5cf118931b2ee8fd37b7d5',
    messagingSenderId: '511513353168',
    projectId: 'auto-my-new',
    authDomain: 'auto-my-new.firebaseapp.com',
    storageBucket: 'auto-my-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjN2lsEMlMGKGGtdp6BcAVU6n-gniY8Ok',
    appId: '1:511513353168:android:3ff55a4f45eaa0ef37b7d5',
    messagingSenderId: '511513353168',
    projectId: 'auto-my-new',
    storageBucket: 'auto-my-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATMjvLeYsZh-4RHxZDo3gVqiWFJwaAr5A',
    appId: '1:511513353168:ios:171e0a9b1a9ebd2937b7d5',
    messagingSenderId: '511513353168',
    projectId: 'auto-my-new',
    storageBucket: 'auto-my-new.appspot.com',
    iosClientId: '511513353168-3gt8rok1lsig2g8iokrdsc2c8bsmte8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTask',
  );
}
